apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-server
spec:
  progressDeadlineSeconds: 60
  replicas: 2

  selector:
    matchLabels:
      app: backend-server
  template:
    metadata:
      labels:
        app: backend-server
    spec:
      containers:
        - name: backend-server
          image: public.ecr.aws/s9e3l8e0/ce-team-project-backend:31
          resources:
            # limits:
            #   memory: "128Mi"
            #   cpu: "500m"
          ports:
          - containerPort: 8080
