apiVersion: v1
kind: Service
metadata:
- name: backend-server
  labels:
    app.kubernetes.io/part-of: cat-service
  annotations:
    prometheus.io/port: "metrics-port"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: backend-server
  ports:
    - name: metrics-port
      protocol: TCP
      port: 5005
      targetPort: 8080
  type: LoadBalancer
