apiVersion: v1
kind: Service
metadata:
  name: backend-server
  labels:
    app.kubernetes.io/part-of: backend-server
  annotations:
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: metrics
    prometheus.io/scrape: "true"
spec:
  selector:
    app: backend-server
  ports:
    - name: metrics
      protocol: TCP
      port: 5005
      targetPort: 8080
  type: LoadBalancer
