apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-server
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: backend-server
  template:
    metadata:
      labels:
        app: backend-server
    spec:
      containers:
        - name: backend-server
          image: nathdu/vapourops-backend:1.0.0
          resources:
            # limits:
            #   memory: "128Mi"
            #   cpu: "500m"
          ports:
          - containerPort: 8080
