apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-server-monitor
  namespace: default
spec:
  endpoints:
    - interval: 10s
      port: metrics-port
      metrics_path: "actuator/metrics"
      scrapeTimeout: 9s
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/part-of: backend-server
