apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
        - name: backend-deployment
          image: public.ecr.aws/s9e3l8e0/ce-team-project-backend:39
          resources:
            # limits:
            #   memory: "128Mi"
            #   cpu: "500m"
          ports:
          - containerPort: 8080
