apiVersion: v1
kind: Service
metadata:
  name: VapourOps-Frontend
spec:
  selector:
    app: VapourOps-Frontend
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 80
  type: LoadBalancer
